name: POSXpert
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1 # Update to the latest version
  flutter_native_splash: ^2.4.3
  flutter_screenutil: ^5.0.0
  
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/pos.png # Ensure the logo image is included
    - assets/images/image1.png

flutter_native_splash:
  color: "#363753" # Set the background color
  image: assets/images/pos.png # Path to your logo
  android: true
  ios: true
  web: true