// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKJ3gFyonye00K8AdT2hC9xQ2uJP86Fcg',
    appId: '1:569568873949:web:3378da4210a6672603ba34',
    messagingSenderId: '569568873949',
    projectId: 'posxpert-d6764',
    authDomain: 'posxpert-d6764.firebaseapp.com',
    storageBucket: 'posxpert-d6764.firebasestorage.app',
    measurementId: 'G-3LL36640DE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9_eX3cDriukD5TOBY9pboghcPLzuuykw',
    appId: '1:569568873949:android:0f196bfe57553e3e03ba34',
    messagingSenderId: '569568873949',
    projectId: 'posxpert-d6764',
    storageBucket: 'posxpert-d6764.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjkHoX0iulVD1fOzaqmCKeQZxvAVcffNI',
    appId: '1:569568873949:ios:708f145c9d49e60803ba34',
    messagingSenderId: '569568873949',
    projectId: 'posxpert-d6764',
    storageBucket: 'posxpert-d6764.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjkHoX0iulVD1fOzaqmCKeQZxvAVcffNI',
    appId: '1:569568873949:ios:708f145c9d49e60803ba34',
    messagingSenderId: '569568873949',
    projectId: 'posxpert-d6764',
    storageBucket: 'posxpert-d6764.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKJ3gFyonye00K8AdT2hC9xQ2uJP86Fcg',
    appId: '1:569568873949:web:4df539d30b6f83ef03ba34',
    messagingSenderId: '569568873949',
    projectId: 'posxpert-d6764',
    authDomain: 'posxpert-d6764.firebaseapp.com',
    storageBucket: 'posxpert-d6764.firebasestorage.app',
    measurementId: 'G-FD2BYDMBBR',
  );

}